use_frameworks!

platform :ios, '10.0'

target 'ZLFlexKit_Example' do
  pod 'ZLFlexKit', :path => '../'
  pod 'SnapKit', '~> 5.0''
  target 'ZLFlexKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
